<?php

namespace AppBundle\Repository;

/**
 * bloccoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bloccoRepository extends \Doctrine\ORM\EntityRepository
{
}
