<?php

namespace AppBundle\Repository;

/**
 * DatiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatiRepository extends \Doctrine\ORM\EntityRepository
{
}
